config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  resources :products do
    resources :comments
  end
  resources :users
  
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/index'

  post 'static_pages/thank_you'
  post 'payments/create'

  root 'static_pages#landing_page'

  mount ActionCable.server => '/cable'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments

	def average_rating
		comments.average(:rating).to_f
	end

	validates :name, presence: true
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  respond_to :json, :html
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where('name ' + (Rails.env.development? ? 'LIKE' : 'ilike') + ' ?', "%#{search_term}%")
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
  end

app/helpers/products_helper.rb
module ProductsHelper
  def show_products(products)
    if products.length > 0
      render partial: products
    else
      ("<div class='card' role='alert'><h4>Sorry! No products were found. Please search again.</h4></div>").html_safe
    end
  end

  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
	<% @comments.each do |comment| %>
		<div>
			<p>
    		<%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
    		<% if signed_in? && current_user.admin? %>
        	<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    		<% end %>
			</p>
			<p class="rated" data-score="<%= comment.rating %>"><%= "(#{comment.rating}/5) " %></p>
			<p><%= comment.body %></p>
				<hr>
			</div>
	<% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product, html: {class: 'form-horizontal' }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Name:", class: "col-sm-1 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description:", class: "col-sm-1 control-label" %>
    <div class="col-sm-6">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image_url, "Image URL:", class: "col-sm-1 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :image_url, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :colour, "Colour:", class: "col-sm-1 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :colour, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, "Price:", class: "col-sm-1 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :price, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
  <h3>Add a review:</h3>
    <p>
      <%= f.label :body, "Your comments" %><br>
      <%= f.text_area :body, class: "form-control" %>
    </p>
    <p>
    	<div class="rating">
      </div>
    </p>  
    <p>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
	<div class="col-xs-12 col-sm-4 text-center">
		<div class="product-title"><%= product.name %></div>
			<%= image_tag(product.image_url, class: "img-responsive featured-product") %>
		<div class="product-desc"><%= product.description %></div>
		<div class="product-price">Retail Price <%= number_to_currency(product.price) %></div>
		<div><%= link_to product, class:"btn btn-default", role:"button" do %>
	      	Tell me more!
	      <% end %> 
	  </div>

		<hr>
		
	</div><!-- /col -->
<% end %>

app/views/products/edit.html.erb
<div class="content">
	<h1>Edit Product</h1>

	<%= render 'form' %>
		
	<%= link_to 'Show', @product, class: "btn btn-forms" %>
	<%= link_to 'Back', products_path, class: "btn btn-forms" %>
	<%= link_to 'Home Page', controller: "static_pages", action: "landing_page" %>

</div>

app/views/products/index.html.erb
<div class="content">
  <h1>Our Products</h1>
  
  <div class="container-fluid">
    <div class="row">
      <%= show_products(@products) %>
    </div>
  </div>
  <br>
  <div class="col-sm-12">
    <%= link_to 'New Product', new_product_path, class: "btn btn-forms" if ( signed_in?) %>
  </div>
</div>

app/views/products/indexOLD.html.erb
<p id="notice"><%= notice %></p>
  <div class="page-title">Our Products</div>
  <div class="container-fluid">
    <div class="row">
      <%= render @products %>
          </div>
          <div class="product-tools">
            <%= link_to 'Show', product, class: 'link-to' %>
            <%= link_to 'Edit', edit_product_path(product), class: 'link-to' %>
            <%= link_to 'Destroy', product, class: 'link-to', method: :delete, data: { confirm: 'Are you sure?' } %>
          </div><!-- /row -->
        </div><!-- /container -->

    <% end %>

  <br>

  <div class="col-sm-12">
  <%= link_to 'New Product', new_product_path %>
  </div>
</div>

app/views/products/new.html.erb
<div class="content">
	<h1>New Product</h1>

	<%= render 'form' %>

	<%= link_to 'Back', products_path, class: "btn btn-forms" %>
</div>

app/views/products/show.html.erb
<div class="content">
  <div class="col-sm-6" >
    <div style="vertical-align: middle; border: none;"><%= image_tag(@product.image_url, class: "img-responsive img-zoom product-img", data_zoom_image: "@product.image_url" ) %>
    </div>
  </div>
    
    <div class="col-sm-6" data-product-id="<%= @product.id %>">
      <% cache @product do %>
        <h2><%= @product.name %></h2>
        <h4><%= @product.description %></h4>
        <br><span class="product-price">Color:</span> <%= @product.colour %>
        <br><br><span class="product-price">Retail Price:</span> <%= number_to_currency(@product.price) %></span>
      <% end %>
    <div>
      <% if user_signed_in? %>
        <%= form_tag "/payments/create" do %>
          <%= render partial: "shared/stripe_checkout_button" %>
            <%= hidden_field_tag(:product_id, @product.id) %>
        <% end %>
      <% end %>
    </div>
    <hr  class="hr-dashed">
    <div>
      <h3>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></h3>
    </div>
    <div>
      <h3>Customer Ratings & Comments:</h3>
      <%= render 'comments' %>
      <%= will_paginate @comments %>
      <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!
    </div>
        <div>
          <%= render 'new_comment' %>
        </div>
    </div>
  </div>
  <div class="col-sm-12">      
    <%= link_to 'Back', products_path, class: "btn btn-forms" %>
    <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-forms" if ( signed_in?) %>
    
  </div>

</div>