config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  
  resources :products do
    resources :comments
  end
  resources :users
  
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/index'

  post 'static_pages/thank_you'
  post 'payments/create'

  root 'static_pages#landing_page'

  mount ActionCable.server => '/cable'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>bikes by laura</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= csrf_meta_tags %><script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon">
</head>

<body>
  <!-- NAVBAR -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="nav-home">
          <a href="/">bikes by laura</a>
        </div><!--end nav-home-->
      </div><!-- end navbar-header -->
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav pull-right">
          <li>
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          <% else %>
            <%= link_to('Login', new_user_session_path) %>
          <% end %>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right nav-other">
          <li><%= link_to "Buy a Bike", products_path %></li>
          <li><%= link_to "About", static_pages_about_path %></li>
          <li><%= link_to "Get in Touch", static_pages_contact_path %></li>
          <li>
          <%= form_tag("/products", method: "get", class: "navbar-form navbar-right nav-form", role: "Search") do %>
            <%= text_field_tag(:q, "", placeholder: "Search", size: "15", class: "nav-search") %>
            <%= submit_tag("Go!", class: "btn btn-primary nav-button") %>
          <% end %></li>
        </ul>
      </div><!-- end navbar collapse -->
    </div><!-- end nav container -->
  </nav><!-- end navbar --> 

  <!-- NOTICES & ALERTS -->
  <% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p id="alert" class="alert alert-info"><%= alert %></p>
  <% end %>


  <!-- BODY -->
  <div>
  <%= yield %>
  </div>

<!-- FOOTER -->
  <div class="footer">
    <div class="container-fluid">
      <div class="col-xs-6">
        &copy; Laura Theis &nbsp;
        <a href="https://twitter.com/intent/tweet?screen_name=lltheis" class="twitter-mention-button" data-show-count="false">Tweet to @lltheis</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
      <div class="col-xs-6 footer-right">
         I learned this on: <a href="http://careerfoundry.com/en" target="_blank"><%= image_tag("CareerFoundry.png", class: "img-responsive footer-image") %></a>     
      </div>
    </div>
  </div>

</body>
</html>